set_property SRC_FILE_INFO {cfile:C:/v22.2/FEB_uController/FEB_uController.srcs/constrs_1/new/uController_wrapper.xdc rfile:../../../FEB_uController.srcs/constrs_1/new/uController_wrapper.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets uController_i/clk_wiz_1/inst/clk_in1_uController_clk_wiz_1_2]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ddr_clock_IBUF]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports GPI1_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports PulseSel_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B3 [get_ports Pulse_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports ddr_clock]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list uController_i/FEB_fabric_0/U0/LEDSrc]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list uController_i/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/GPOCount[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/GPOCount[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/GPOCount[2]}]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[2]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[3]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[4]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[5]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[6]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[7]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOffTime[8]}]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[2]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[3]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[4]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[5]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[6]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[7]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[8]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[9]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[10]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TrigType[11]}]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[2]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[3]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[4]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[5]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[6]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[7]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[8]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[9]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[10]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[11]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[12]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[13]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[14]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[15]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[16]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[17]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[18]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[19]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[20]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[21]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[22]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[23]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[24]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[25]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[26]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[27]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[28]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[29]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[30]} {uController_i/FEB_fabric_0/U0/Trigger_logic/uBunch[31]}]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[2]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[3]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[4]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[5]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[6]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[7]} {uController_i/FEB_fabric_0/U0/Trigger_logic/LEDTime[8]}]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[2]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[3]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[4]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[5]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[6]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[7]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[8]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[9]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[10]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[11]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[12]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[13]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[14]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[15]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[16]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[17]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[18]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[19]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[20]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[21]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[22]} {uController_i/FEB_fabric_0/U0/Trigger_logic/Rx1DatReg[23]}]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[0]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[1]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[2]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[3]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[4]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[5]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[6]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[7]} {uController_i/FEB_fabric_0/U0/Trigger_logic/TurnOnTime[8]}]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/BeamOn]]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/FlashEn]]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/FlashGate]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/GPO]]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/LEDSrc]]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/PulseSel]]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/SlfTrgEn]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/TmgSrcSel]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/TrigReq]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/TrigReqD]]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/uBunchGuard]]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list uController_i/FEB_fabric_0/U0/Trigger_logic/uBunchWrt]]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
