set_property SRC_FILE_INFO {cfile:C:/v22.2/FEB_uController/FEB_uController.srcs/constrs_1/new/uController_wrapper.xdc rfile:../../../FEB_uController.srcs/constrs_1/new/uController_wrapper.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets uController_i/clk_wiz_1/inst/clk_in1_uController_clk_wiz_1_2]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ddr_clock_IBUF]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports GPI1_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports PulseSel_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B3 [get_ports Pulse_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports ddr_clock]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list uController_i/FEB_fabric_0/U0/LEDSrc]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe10 [get_nets [list uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/n_0_0]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe11 [get_nets [list uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/n_0_1]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[0]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[1]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[2]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[3]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[4]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[5]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[6]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[7]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[8]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[9]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[10]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[11]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[12]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[13]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[14]} {uController_i/FEB_fabric_0/U0/AFE_Interface/ActiveTime[15]}]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[0]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[1]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[2]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[3]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[4]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[5]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[6]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[7]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[8]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[9]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[10]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[11]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[12]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[13]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[14]} {uController_i/FEB_fabric_0/U0/AFE_Interface/delay[15]}]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[0]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[1]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[2]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[3]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[4]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[5]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[6]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[7]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[8]} {uController_i/FEB_fabric_0/U0/AFE_Interface/AFEemuWRaddr[9]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list uController_i/FEB_fabric_0/U0/AFE_Interface/start]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_En[0][7]}]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][13]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][14]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferIn[0][0][15]}]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe4 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_Req[0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Avg_Req[1]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe5 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferWE[0][7]}]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe6 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Input_Seqs[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Input_Seqs[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Input_Seqs[0][0][2]}]]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe7 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Diff_Reg[0][0][13]}]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe8 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/IntTrgThresh[0][0][13]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe9 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Pad_Avg_Count[0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Pad_Avg_Count[0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Pad_Avg_Count[0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Pad_Avg_Count[0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Pad_Avg_Count[0][4]}]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe10 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][13]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][14]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Avg[0][0][15]}]]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe11 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/SlfTrgEdge[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/SlfTrgEdge[0][0][1]}]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe12 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/Ped_Reg[0][0][13]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe13 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/din_AFE[0][0][13]}]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe14 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][9]}]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe15 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/dout_AFE[0][0][13]}]]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe16 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/uBunchOffset[0][11]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][9]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][10]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][11]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][12]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][13]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][14]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferOut[0][0][15]}]]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][4]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][5]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][6]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][7]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][8]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/BufferRdAdd[0][0][9]}]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe2 [get_nets [list {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/PortNo[0]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/PortNo[1]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/PortNo[2]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/PortNo[3]} {uController_i/FEB_fabric_0/U0/AFE_DataPath_inst/PortNo[4]}]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[9]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[14]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[1]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[12]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[13]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[6]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[0]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[2]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[7]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[8]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[15]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[3]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[4]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[5]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[10]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[11]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[0]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[4]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[7]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[9]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[14]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[15]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[2]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[6]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[8]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[10]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[5]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[11]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[12]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[1]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[3]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[13]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[0]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[1]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[2]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[3]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[4]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[5]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[6]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[7]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[8]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[9]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[10]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[11]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[12]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[13]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[14]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdin[15]}]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[0]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[1]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[2]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[3]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[4]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[5]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[6]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[7]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[8]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[9]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[10]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[11]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[12]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[13]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[14]} {uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOdout[15]}]]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOempty]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOfull]]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOrde]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list uController_i/FEB_fabric_0/U0/data_back_AFE/iuCD_FIFOwre]]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list uController_i/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/AFE_Num[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/AFE_Num[1]}]]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Chan_Num[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Chan_Num[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Chan_Num[2]}]]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[3]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[4]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[5]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[6]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[7]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[8]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[9]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[10]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[11]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[12]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[13]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[14]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffDat[15]}]]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Event_Builder[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Event_Builder[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Event_Builder[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Event_Builder[3]}]]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[3]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[4]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[5]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[6]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[7]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[8]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[9]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[10]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[11]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[12]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[13]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[14]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EventWdCnt[15]}]]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[3]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[4]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[5]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[6]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[7]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[8]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[9]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[10]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[11]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[12]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[13]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[14]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffOut[15]}]]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[3]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[4]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[5]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[6]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[7]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[8]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[9]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWdsUsed[10]}]]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Read_Seq_Stat[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Read_Seq_Stat[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Read_Seq_Stat[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/Read_Seq_Stat[3]}]]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[0]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[1]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[2]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[3]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[4]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[5]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[6]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[7]} {uController_i/FEB_fabric_0/U0/EventBuilder_logic/SampleCount[8]}]]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffRd]]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list uController_i/FEB_fabric_0/U0/EventBuilder_logic/EvBuffWrt]]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
