# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# XDC: new/timing.xdc

# Block Designs: bd/BareMetal_TestDDR/BareMetal_TestDDR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BareMetal_TestDDR || ORIG_REF_NAME==BareMetal_TestDDR} -quiet] -quiet

# IP: bd/BareMetal_TestDDR/ip/BareMetal_TestDDR_TestDDR_top_0_0/BareMetal_TestDDR_TestDDR_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BareMetal_TestDDR_TestDDR_top_0_0 || ORIG_REF_NAME==BareMetal_TestDDR_TestDDR_top_0_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/DDR3LController/DDR3LController.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: ip/SCFIFO_1kx16/SCFIFO_1kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1kx16 || ORIG_REF_NAME==SCFIFO_1kx16} -quiet] -quiet

# IP: ip/SCFIFO_32x256/SCFIFO_32x256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# IP: bd/BareMetal_TestDDR/ip/BareMetal_TestDDR_clk_wiz_0_4/BareMetal_TestDDR_clk_wiz_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BareMetal_TestDDR_clk_wiz_0_4 || ORIG_REF_NAME==BareMetal_TestDDR_clk_wiz_0_4} -quiet] -quiet

# XDC: c:/v22.2/Test_DDR/Test_DDR.gen/sources_1/bd/BareMetal_TestDDR/BareMetal_TestDDR_ooc.xdc
