# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/bd/ARTY_TestDDR/ip/ARTY_TestDDR_xbar_0/ARTY_TestDDR_xbar_0.xci
# IP: The module: 'ARTY_TestDDR_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v22.2/Test_DDR/Test_DDR.gen/sources_1/bd/ARTY_TestDDR/ip/ARTY_TestDDR_xbar_0/ARTY_TestDDR_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_TestDDR_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/bd/ARTY_TestDDR/ip/ARTY_TestDDR_xbar_0/ARTY_TestDDR_xbar_0.xci
# IP: The module: 'ARTY_TestDDR_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v22.2/Test_DDR/Test_DDR.gen/sources_1/bd/ARTY_TestDDR/ip/ARTY_TestDDR_xbar_0/ARTY_TestDDR_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_TestDDR_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
