# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v22.2/FEB_AXI_test/FEB_AXI_test.srcs/sources_1/bd/ARTY_test/ip/ARTY_test_FEB_test_0_0/ARTY_test_FEB_test_0_0.xci
# IP: The module: 'ARTY_test_FEB_test_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/FEB_AXI_test/FEB_AXI_test.srcs/sources_1/ip/AFEemu/AFEemu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet

# IP: c:/v22.2/FEB_AXI_test/FEB_AXI_test.srcs/sources_1/bd/ARTY_test/ip/ARTY_test_FEB_test_0_0/ARTY_test_FEB_test_0_0.xci
# IP: The module: 'ARTY_test_FEB_test_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/FEB_AXI_test/FEB_AXI_test.srcs/sources_1/ip/AFEemu/AFEemu.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet
