# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0.xci
# IP: The module: 'uController_clk_wiz_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController_clk_wiz_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController_clk_wiz_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController_clk_wiz_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0.xci
# IP: The module: 'uController_clk_wiz_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController_clk_wiz_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController_clk_wiz_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_3_0/uController_clk_wiz_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController_clk_wiz_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
