set_property SRC_FILE_INFO {cfile:C:/v22.2/FEB_fabric/FEB_fabric.srcs/constrs_1/new/pinout.xdc rfile:../../../FEB_fabric.srcs/constrs_1/new/pinout.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/v22.2/FEB_fabric/FEB_fabric.srcs/constrs_1/new/timing.xdc rfile:../../../FEB_fabric.srcs/constrs_1/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {GA[1]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {GA[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {uCA[11]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports {uCA[10]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {uCA[9]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R15 [get_ports {uCA[8]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {uCA[7]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {uCA[6]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P13 [get_ports {uCA[5]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R13 [get_ports {uCA[4]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {uCA[3]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {uCA[2]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {uCA[1]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {uCA[0]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports {uCD[15]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T13 [get_ports {uCD[14]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R11 [get_ports {uCD[13]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports {uCD[11]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13 [get_ports {uCD[10]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports {uCD[12]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports {uCD[9]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {uCD[8]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {uCD[7]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {uCD[6]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {uCD[5]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {uCD[4]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {uCD[3]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports {uCD[2]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {uCD[1]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {uCD[0]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports CpldCS]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports CpldRst]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports uCRd]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports uCWr]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CpldRst_IBUF]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks Clk_200MHz] -to [get_clocks clk_pll_i]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports Clk_100MHz]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports Clk_200MHz]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports SysClk]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports GPI0_P]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports GPI1]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports Pulse]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports PulseSel]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports Clk_80MHz]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list LEDSrc]]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list Clk_80MHz_IBUF_BUFG]]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {AFE_DataPath_inst/BufferWE[0][0]} {AFE_DataPath_inst/BufferWE[0][1]} {AFE_DataPath_inst/BufferWE[0][2]} {AFE_DataPath_inst/BufferWE[0][3]} {AFE_DataPath_inst/BufferWE[0][4]} {AFE_DataPath_inst/BufferWE[0][5]} {AFE_DataPath_inst/BufferWE[0][6]} {AFE_DataPath_inst/BufferWE[0][7]}]]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {AFE_DataPath_inst/Avg_En[0][0]} {AFE_DataPath_inst/Avg_En[0][1]} {AFE_DataPath_inst/Avg_En[0][2]} {AFE_DataPath_inst/Avg_En[0][3]} {AFE_DataPath_inst/Avg_En[0][4]} {AFE_DataPath_inst/Avg_En[0][5]} {AFE_DataPath_inst/Avg_En[0][6]} {AFE_DataPath_inst/Avg_En[0][7]}]]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {AFE_DataPath_inst/BufferWrtAdd[0][0][0]} {AFE_DataPath_inst/BufferWrtAdd[0][0][1]} {AFE_DataPath_inst/BufferWrtAdd[0][0][2]} {AFE_DataPath_inst/BufferWrtAdd[0][0][3]} {AFE_DataPath_inst/BufferWrtAdd[0][0][4]} {AFE_DataPath_inst/BufferWrtAdd[0][0][5]} {AFE_DataPath_inst/BufferWrtAdd[0][0][6]} {AFE_DataPath_inst/BufferWrtAdd[0][0][7]} {AFE_DataPath_inst/BufferWrtAdd[0][0][8]} {AFE_DataPath_inst/BufferWrtAdd[0][0][9]}]]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {AFE_DataPath_inst/Avg_Req[0]} {AFE_DataPath_inst/Avg_Req[1]}]]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {AFE_DataPath_inst/BufferIn[0][0][0]} {AFE_DataPath_inst/BufferIn[0][0][1]} {AFE_DataPath_inst/BufferIn[0][0][2]} {AFE_DataPath_inst/BufferIn[0][0][3]} {AFE_DataPath_inst/BufferIn[0][0][4]} {AFE_DataPath_inst/BufferIn[0][0][5]} {AFE_DataPath_inst/BufferIn[0][0][6]} {AFE_DataPath_inst/BufferIn[0][0][7]} {AFE_DataPath_inst/BufferIn[0][0][8]} {AFE_DataPath_inst/BufferIn[0][0][9]} {AFE_DataPath_inst/BufferIn[0][0][10]} {AFE_DataPath_inst/BufferIn[0][0][11]} {AFE_DataPath_inst/BufferIn[0][0][12]} {AFE_DataPath_inst/BufferIn[0][0][13]} {AFE_DataPath_inst/BufferIn[0][0][14]} {AFE_DataPath_inst/BufferIn[0][0][15]}]]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {AFE_DataPath_inst/InWdCnt[0][0][0]} {AFE_DataPath_inst/InWdCnt[0][0][1]} {AFE_DataPath_inst/InWdCnt[0][0][2]} {AFE_DataPath_inst/InWdCnt[0][0][3]} {AFE_DataPath_inst/InWdCnt[0][0][4]} {AFE_DataPath_inst/InWdCnt[0][0][5]} {AFE_DataPath_inst/InWdCnt[0][0][6]} {AFE_DataPath_inst/InWdCnt[0][0][7]} {AFE_DataPath_inst/InWdCnt[0][0][8]} {AFE_DataPath_inst/InWdCnt[0][0][9]}]]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {AFE_DataPath_inst/Pad_Avg_Count[0][0]} {AFE_DataPath_inst/Pad_Avg_Count[0][1]} {AFE_DataPath_inst/Pad_Avg_Count[0][2]} {AFE_DataPath_inst/Pad_Avg_Count[0][3]} {AFE_DataPath_inst/Pad_Avg_Count[0][4]}]]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {AFE_DataPath_inst/Input_Seqs[0][0][0]} {AFE_DataPath_inst/Input_Seqs[0][0][1]} {AFE_DataPath_inst/Input_Seqs[0][0][2]}]]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {AFE_DataPath_inst/IntTrgThresh[0][0][0]} {AFE_DataPath_inst/IntTrgThresh[0][0][1]} {AFE_DataPath_inst/IntTrgThresh[0][0][2]} {AFE_DataPath_inst/IntTrgThresh[0][0][3]} {AFE_DataPath_inst/IntTrgThresh[0][0][4]} {AFE_DataPath_inst/IntTrgThresh[0][0][5]} {AFE_DataPath_inst/IntTrgThresh[0][0][6]} {AFE_DataPath_inst/IntTrgThresh[0][0][7]} {AFE_DataPath_inst/IntTrgThresh[0][0][8]} {AFE_DataPath_inst/IntTrgThresh[0][0][9]} {AFE_DataPath_inst/IntTrgThresh[0][0][10]} {AFE_DataPath_inst/IntTrgThresh[0][0][11]} {AFE_DataPath_inst/IntTrgThresh[0][0][12]} {AFE_DataPath_inst/IntTrgThresh[0][0][13]}]]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {AFE_DataPath_inst/Ped_Avg[0][0][0]} {AFE_DataPath_inst/Ped_Avg[0][0][1]} {AFE_DataPath_inst/Ped_Avg[0][0][2]} {AFE_DataPath_inst/Ped_Avg[0][0][3]} {AFE_DataPath_inst/Ped_Avg[0][0][4]} {AFE_DataPath_inst/Ped_Avg[0][0][5]} {AFE_DataPath_inst/Ped_Avg[0][0][6]} {AFE_DataPath_inst/Ped_Avg[0][0][7]} {AFE_DataPath_inst/Ped_Avg[0][0][8]} {AFE_DataPath_inst/Ped_Avg[0][0][9]} {AFE_DataPath_inst/Ped_Avg[0][0][10]} {AFE_DataPath_inst/Ped_Avg[0][0][11]} {AFE_DataPath_inst/Ped_Avg[0][0][12]} {AFE_DataPath_inst/Ped_Avg[0][0][13]} {AFE_DataPath_inst/Ped_Avg[0][0][14]} {AFE_DataPath_inst/Ped_Avg[0][0][15]}]]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {AFE_DataPath_inst/Ped_Reg[0][0][0]} {AFE_DataPath_inst/Ped_Reg[0][0][1]} {AFE_DataPath_inst/Ped_Reg[0][0][2]} {AFE_DataPath_inst/Ped_Reg[0][0][3]} {AFE_DataPath_inst/Ped_Reg[0][0][4]} {AFE_DataPath_inst/Ped_Reg[0][0][5]} {AFE_DataPath_inst/Ped_Reg[0][0][6]} {AFE_DataPath_inst/Ped_Reg[0][0][7]} {AFE_DataPath_inst/Ped_Reg[0][0][8]} {AFE_DataPath_inst/Ped_Reg[0][0][9]} {AFE_DataPath_inst/Ped_Reg[0][0][10]} {AFE_DataPath_inst/Ped_Reg[0][0][11]} {AFE_DataPath_inst/Ped_Reg[0][0][12]} {AFE_DataPath_inst/Ped_Reg[0][0][13]}]]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {AFE_DataPath_inst/SlfTrgEdge[0][0][0]} {AFE_DataPath_inst/SlfTrgEdge[0][0][1]}]]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {AFE_DataPath_inst/dout_AFE[0][0][0]} {AFE_DataPath_inst/dout_AFE[0][0][1]} {AFE_DataPath_inst/dout_AFE[0][0][2]} {AFE_DataPath_inst/dout_AFE[0][0][3]} {AFE_DataPath_inst/dout_AFE[0][0][4]} {AFE_DataPath_inst/dout_AFE[0][0][5]} {AFE_DataPath_inst/dout_AFE[0][0][6]} {AFE_DataPath_inst/dout_AFE[0][0][7]} {AFE_DataPath_inst/dout_AFE[0][0][8]} {AFE_DataPath_inst/dout_AFE[0][0][9]} {AFE_DataPath_inst/dout_AFE[0][0][10]} {AFE_DataPath_inst/dout_AFE[0][0][11]} {AFE_DataPath_inst/dout_AFE[0][0][12]} {AFE_DataPath_inst/dout_AFE[0][0][13]}]]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {AFE_DataPath_inst/din_AFE[0][0][0]} {AFE_DataPath_inst/din_AFE[0][0][1]} {AFE_DataPath_inst/din_AFE[0][0][2]} {AFE_DataPath_inst/din_AFE[0][0][3]} {AFE_DataPath_inst/din_AFE[0][0][4]} {AFE_DataPath_inst/din_AFE[0][0][5]} {AFE_DataPath_inst/din_AFE[0][0][6]} {AFE_DataPath_inst/din_AFE[0][0][7]} {AFE_DataPath_inst/din_AFE[0][0][8]} {AFE_DataPath_inst/din_AFE[0][0][9]} {AFE_DataPath_inst/din_AFE[0][0][10]} {AFE_DataPath_inst/din_AFE[0][0][11]} {AFE_DataPath_inst/din_AFE[0][0][12]} {AFE_DataPath_inst/din_AFE[0][0][13]}]]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][0]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][1]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][2]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][3]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][4]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][5]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][6]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][7]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][8]} {AFE_DataPath_inst/WrtNxtWdCntAd[0][0][9]}]]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][0]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][1]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][2]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][3]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][4]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][5]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][6]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][7]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][8]} {AFE_DataPath_inst/WrtCrrntWdCntAd[0][0][9]}]]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {AFE_DataPath_inst/uBunchOffset[0][0]} {AFE_DataPath_inst/uBunchOffset[0][1]} {AFE_DataPath_inst/uBunchOffset[0][2]} {AFE_DataPath_inst/uBunchOffset[0][3]} {AFE_DataPath_inst/uBunchOffset[0][4]} {AFE_DataPath_inst/uBunchOffset[0][5]} {AFE_DataPath_inst/uBunchOffset[0][6]} {AFE_DataPath_inst/uBunchOffset[0][7]} {AFE_DataPath_inst/uBunchOffset[0][8]} {AFE_DataPath_inst/uBunchOffset[0][9]} {AFE_DataPath_inst/uBunchOffset[0][10]} {AFE_DataPath_inst/uBunchOffset[0][11]}]]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {AFE_DataPath_inst/iWrtDL[1][0]} {AFE_DataPath_inst/iWrtDL[1][1]}]]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {AFE_DataPath_inst/iWrtDL[0][0]} {AFE_DataPath_inst/iWrtDL[0][1]}]]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {AFE_DataPath_inst/uBunchOffset[1][0]} {AFE_DataPath_inst/uBunchOffset[1][1]} {AFE_DataPath_inst/uBunchOffset[1][2]} {AFE_DataPath_inst/uBunchOffset[1][3]} {AFE_DataPath_inst/uBunchOffset[1][4]} {AFE_DataPath_inst/uBunchOffset[1][5]} {AFE_DataPath_inst/uBunchOffset[1][6]} {AFE_DataPath_inst/uBunchOffset[1][7]} {AFE_DataPath_inst/uBunchOffset[1][8]} {AFE_DataPath_inst/uBunchOffset[1][9]} {AFE_DataPath_inst/uBunchOffset[1][10]} {AFE_DataPath_inst/uBunchOffset[1][11]}]]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {AFE_DataPath_inst/ADCSmplCntr[0][0][0]} {AFE_DataPath_inst/ADCSmplCntr[0][0][1]} {AFE_DataPath_inst/ADCSmplCntr[0][0][2]} {AFE_DataPath_inst/ADCSmplCntr[0][0][3]}]]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {AFE_DataPath_inst/ADCSmplGate[0]} {AFE_DataPath_inst/ADCSmplGate[1]}]]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list SysClk_IBUF_BUFG]]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {Trigger_logic/GateCounter[0]} {Trigger_logic/GateCounter[1]} {Trigger_logic/GateCounter[2]} {Trigger_logic/GateCounter[3]} {Trigger_logic/GateCounter[4]} {Trigger_logic/GateCounter[5]} {Trigger_logic/GateCounter[6]} {Trigger_logic/GateCounter[7]} {Trigger_logic/GateCounter[8]}]]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {Trigger_logic/TrigType[0]} {Trigger_logic/TrigType[1]} {Trigger_logic/TrigType[2]} {Trigger_logic/TrigType[3]} {Trigger_logic/TrigType[4]} {Trigger_logic/TrigType[5]} {Trigger_logic/TrigType[6]} {Trigger_logic/TrigType[7]} {Trigger_logic/TrigType[8]} {Trigger_logic/TrigType[9]} {Trigger_logic/TrigType[10]} {Trigger_logic/TrigType[11]}]]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list {Trigger_logic/uBunch[0]} {Trigger_logic/uBunch[1]} {Trigger_logic/uBunch[2]} {Trigger_logic/uBunch[3]} {Trigger_logic/uBunch[4]} {Trigger_logic/uBunch[5]} {Trigger_logic/uBunch[6]} {Trigger_logic/uBunch[7]} {Trigger_logic/uBunch[8]} {Trigger_logic/uBunch[9]} {Trigger_logic/uBunch[10]} {Trigger_logic/uBunch[11]} {Trigger_logic/uBunch[12]} {Trigger_logic/uBunch[13]} {Trigger_logic/uBunch[14]} {Trigger_logic/uBunch[15]} {Trigger_logic/uBunch[16]} {Trigger_logic/uBunch[17]} {Trigger_logic/uBunch[18]} {Trigger_logic/uBunch[19]} {Trigger_logic/uBunch[20]} {Trigger_logic/uBunch[21]} {Trigger_logic/uBunch[22]} {Trigger_logic/uBunch[23]} {Trigger_logic/uBunch[24]} {Trigger_logic/uBunch[25]} {Trigger_logic/uBunch[26]} {Trigger_logic/uBunch[27]} {Trigger_logic/uBunch[28]} {Trigger_logic/uBunch[29]} {Trigger_logic/uBunch[30]} {Trigger_logic/uBunch[31]}]]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list {Trigger_logic/GPOCount[0]} {Trigger_logic/GPOCount[1]} {Trigger_logic/GPOCount[2]}]]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe4 [get_nets [list {Trigger_logic/TurnOffTime[0]} {Trigger_logic/TurnOffTime[1]} {Trigger_logic/TurnOffTime[2]} {Trigger_logic/TurnOffTime[3]} {Trigger_logic/TurnOffTime[4]} {Trigger_logic/TurnOffTime[5]} {Trigger_logic/TurnOffTime[6]} {Trigger_logic/TurnOffTime[7]} {Trigger_logic/TurnOffTime[8]}]]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe5 [get_nets [list {Trigger_logic/TurnOnTime[0]} {Trigger_logic/TurnOnTime[1]} {Trigger_logic/TurnOnTime[2]} {Trigger_logic/TurnOnTime[3]} {Trigger_logic/TurnOnTime[4]} {Trigger_logic/TurnOnTime[5]} {Trigger_logic/TurnOnTime[6]} {Trigger_logic/TurnOnTime[7]} {Trigger_logic/TurnOnTime[8]}]]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe6 [get_nets [list {Trigger_logic/LEDTime[0]} {Trigger_logic/LEDTime[1]} {Trigger_logic/LEDTime[2]} {Trigger_logic/LEDTime[3]} {Trigger_logic/LEDTime[4]} {Trigger_logic/LEDTime[5]} {Trigger_logic/LEDTime[6]} {Trigger_logic/LEDTime[7]} {Trigger_logic/LEDTime[8]}]]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe7 [get_nets [list Trigger_logic/BeamOn]]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe8 [get_nets [list Trigger_logic/FlashEn]]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe9 [get_nets [list Trigger_logic/FlashGate]]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe10 [get_nets [list Trigger_logic/GPO]]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe11 [get_nets [list Trigger_logic/LEDSrc]]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe12 [get_nets [list Trigger_logic/PulseSel]]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe13 [get_nets [list Trigger_logic/SlfTrgEn]]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe14 [get_nets [list Trigger_logic/TmgSrcSel]]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe15 [get_nets [list Trigger_logic/TrigReq]]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe16 [get_nets [list Trigger_logic/uBunchGuard]]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe17 [get_nets [list Trigger_logic/uBunchWrt]]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list CpldRst_IBUF_BUFG]]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list AFE_DataPath_inst/AsyncRst]]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CpldRst_IBUF_BUFG]
