# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/uController.bd
# Block Designs: The module: 'uController' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_v10_0/uController_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_v10_0 || ORIG_REF_NAME==uController_dlmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_v10_0/uController_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_v10_0 || ORIG_REF_NAME==uController_ilmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_bram_if_cntlr_0/uController_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_bram_if_cntlr_0/uController_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_lmb_bram_0 || ORIG_REF_NAME==uController_lmb_bram_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_xbar_0/uController_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_xbar_0 || ORIG_REF_NAME==uController_xbar_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_axi_periph_0/uController_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uController_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_system_ila_0_0 || ORIG_REF_NAME==uController_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b || ORIG_REF_NAME==bd_326b} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_AXI_Interface_0_0/uController_FEB_AXI_Interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_AXI_Interface_0_0 || ORIG_REF_NAME==uController_FEB_AXI_Interface_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/uController_FEB_fabric_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/AFEemu_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu_ila || ORIG_REF_NAME==AFEemu_ila} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila0 || ORIG_REF_NAME==AFE_DataPath_ila0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/AFE_DataPath_ila1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila1 || ORIG_REF_NAME==AFE_DataPath_ila1} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/AFE_DataPath_ila2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila2 || ORIG_REF_NAME==AFE_DataPath_ila2} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/AFE_DataPath_ila3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila3 || ORIG_REF_NAME==AFE_DataPath_ila3} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/EVB_ila0/EVB_ila0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EVB_ila0 || ORIG_REF_NAME==EVB_ila0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/LVDSTxBuff/LVDSTxBuff.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDSTxBuff || ORIG_REF_NAME==LVDSTxBuff} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Hist_Ram/Hist_Ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hist_Ram || ORIG_REF_NAME==Hist_Ram} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/DDR_ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR_ila_0 || ORIG_REF_NAME==DDR_ila_0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPRAM_1Kx16 || ORIG_REF_NAME==DPRAM_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DP_Pipeline || ORIG_REF_NAME==AFE_DP_Pipeline} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Trigger_ila/Trigger_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Trigger_ila || ORIG_REF_NAME==Trigger_ila} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0_ooc_debug.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0_ooc_trace.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFEemu_ila || ORIG_REF_NAME==AFEemu_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/AFEemu_ila_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila0 || ORIG_REF_NAME==AFE_DataPath_ila0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila1 || ORIG_REF_NAME==AFE_DataPath_ila1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/AFE_DataPath_ila1_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila2 || ORIG_REF_NAME==AFE_DataPath_ila2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/AFE_DataPath_ila2_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila3 || ORIG_REF_NAME==AFE_DataPath_ila3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/AFE_DataPath_ila3_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/EVB_ila0/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==EVB_ila0 || ORIG_REF_NAME==EVB_ila0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/EVB_ila0/EVB_ila0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/LVDSTxBuff/LVDSTxBuff.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDSTxBuff || ORIG_REF_NAME==LVDSTxBuff} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Hist_Ram/Hist_Ram_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_ila_0 || ORIG_REF_NAME==DDR_ila_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/DDR_ila_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Trigger_ila/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Trigger_ila || ORIG_REF_NAME==Trigger_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Trigger_ila/Trigger_ila_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/pinout.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/timing.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/uController_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/uController.bd
# Block Designs: The module: 'uController' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_v10_0/uController_dlmb_v10_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_v10_0 || ORIG_REF_NAME==uController_dlmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_v10_0/uController_ilmb_v10_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_v10_0 || ORIG_REF_NAME==uController_ilmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_bram_if_cntlr_0/uController_dlmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_bram_if_cntlr_0/uController_ilmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_lmb_bram_0 || ORIG_REF_NAME==uController_lmb_bram_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_xbar_0/uController_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_xbar_0 || ORIG_REF_NAME==uController_xbar_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_axi_periph_0/uController_microblaze_0_axi_periph_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uController_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_system_ila_0_0 || ORIG_REF_NAME==uController_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b || ORIG_REF_NAME==bd_326b} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_AXI_Interface_0_0/uController_FEB_AXI_Interface_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_AXI_Interface_0_0 || ORIG_REF_NAME==uController_FEB_AXI_Interface_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/uController_FEB_fabric_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/AFEemu_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu_ila || ORIG_REF_NAME==AFEemu_ila} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila0 || ORIG_REF_NAME==AFE_DataPath_ila0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/AFE_DataPath_ila1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila1 || ORIG_REF_NAME==AFE_DataPath_ila1} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/AFE_DataPath_ila2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila2 || ORIG_REF_NAME==AFE_DataPath_ila2} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/AFE_DataPath_ila3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila3 || ORIG_REF_NAME==AFE_DataPath_ila3} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/EVB_ila0/EVB_ila0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EVB_ila0 || ORIG_REF_NAME==EVB_ila0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/LVDSTxBuff/LVDSTxBuff.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDSTxBuff || ORIG_REF_NAME==LVDSTxBuff} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Hist_Ram/Hist_Ram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hist_Ram || ORIG_REF_NAME==Hist_Ram} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/DDR_ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR_ila_0 || ORIG_REF_NAME==DDR_ila_0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPRAM_1Kx16 || ORIG_REF_NAME==DPRAM_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DP_Pipeline || ORIG_REF_NAME==AFE_DP_Pipeline} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Trigger_ila/Trigger_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Trigger_ila || ORIG_REF_NAME==Trigger_ila} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0_ooc_debug.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0_ooc_trace.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFEemu_ila || ORIG_REF_NAME==AFEemu_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/AFEemu_ila_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila0 || ORIG_REF_NAME==AFE_DataPath_ila0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila1 || ORIG_REF_NAME==AFE_DataPath_ila1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/AFE_DataPath_ila1_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila2 || ORIG_REF_NAME==AFE_DataPath_ila2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/AFE_DataPath_ila2_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AFE_DataPath_ila3 || ORIG_REF_NAME==AFE_DataPath_ila3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/AFE_DataPath_ila3_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/EVB_ila0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==EVB_ila0 || ORIG_REF_NAME==EVB_ila0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/EVB_ila0/EVB_ila0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/LVDSTxBuff/LVDSTxBuff.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDSTxBuff || ORIG_REF_NAME==LVDSTxBuff} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Hist_Ram/Hist_Ram_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_ila_0 || ORIG_REF_NAME==DDR_ila_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/DDR_ila_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Trigger_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Trigger_ila || ORIG_REF_NAME==Trigger_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/Trigger_ila/Trigger_ila_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/pinout.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/timing.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/uController_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController'. Do not add the DONT_TOUCH constraint.
