# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/uController.bd
# Block Designs: The module: 'uController' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_v10_0/uController_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_v10_0 || ORIG_REF_NAME==uController_dlmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_v10_0/uController_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_v10_0 || ORIG_REF_NAME==uController_ilmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_bram_if_cntlr_0/uController_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_bram_if_cntlr_0/uController_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_lmb_bram_0 || ORIG_REF_NAME==uController_lmb_bram_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_xbar_0/uController_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_xbar_0 || ORIG_REF_NAME==uController_xbar_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_axi_periph_0/uController_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uController_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_system_ila_0_0 || ORIG_REF_NAME==uController_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b || ORIG_REF_NAME==bd_326b} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_AXI_Interface_0_0/uController_FEB_AXI_Interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_AXI_Interface_0_0 || ORIG_REF_NAME==uController_FEB_AXI_Interface_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/uController_FEB_fabric_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPRAM_1Kx16 || ORIG_REF_NAME==DPRAM_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DP_Pipeline || ORIG_REF_NAME==AFE_DP_Pipeline} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_system_ila_1_0/uController_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_system_ila_1_0 || ORIG_REF_NAME==uController_system_ila_1_0} -quiet] -quiet

# Block Designs: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/bd_f23a.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f23a || ORIG_REF_NAME==bd_f23a} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/bd_f23a_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f23a_ila_lib_0 || ORIG_REF_NAME==bd_f23a_ila_lib_0} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0_ooc_debug.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0_ooc_trace.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/pinout.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/timing.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f23a_ila_lib_0 || ORIG_REF_NAME==bd_f23a_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f23a_ila_lib_0 || ORIG_REF_NAME==bd_f23a_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/bd_f23a_ila_lib_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/bd_f23a_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/uController_system_ila_1_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/uController_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/uController.bd
# Block Designs: The module: 'uController' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_v10_0/uController_dlmb_v10_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_v10_0 || ORIG_REF_NAME==uController_dlmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_v10_0/uController_ilmb_v10_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_v10_0 || ORIG_REF_NAME==uController_ilmb_v10_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_dlmb_bram_if_cntlr_0/uController_dlmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_ilmb_bram_if_cntlr_0/uController_ilmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uController_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_lmb_bram_0 || ORIG_REF_NAME==uController_lmb_bram_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_xbar_0/uController_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_xbar_0 || ORIG_REF_NAME==uController_xbar_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_microblaze_0_axi_periph_0/uController_microblaze_0_axi_periph_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uController_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_system_ila_0_0 || ORIG_REF_NAME==uController_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b || ORIG_REF_NAME==bd_326b} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_AXI_Interface_0_0/uController_FEB_AXI_Interface_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_AXI_Interface_0_0 || ORIG_REF_NAME==uController_FEB_AXI_Interface_0_0} -quiet] -quiet

# IP: C:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/uController_FEB_fabric_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPRAM_1Kx16 || ORIG_REF_NAME==DPRAM_1Kx16} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFE_DP_Pipeline || ORIG_REF_NAME==AFE_DP_Pipeline} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.srcs/sources_1/bd/uController/ip/uController_system_ila_1_0/uController_system_ila_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uController_system_ila_1_0 || ORIG_REF_NAME==uController_system_ila_1_0} -quiet] -quiet

# Block Designs: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/bd_f23a.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f23a || ORIG_REF_NAME==bd_f23a} -quiet] -quiet

# IP: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/bd_f23a_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f23a_ila_lib_0 || ORIG_REF_NAME==bd_f23a_ila_lib_0} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_microblaze_0_0 || ORIG_REF_NAME==uController_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_microblaze_0_0/uController_microblaze_0_0_ooc_debug.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_0_0 || ORIG_REF_NAME==uController_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_0_0/uController_clk_wiz_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_gpio_0_0/uController_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_gpio_0_0 || ORIG_REF_NAME==uController_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_axi_uartlite_0_0/uController_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_axi_uartlite_0_0 || ORIG_REF_NAME==uController_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_lmb_bram_0/uController_lmb_bram_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_mdm_1_0 || ORIG_REF_NAME==uController_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_mdm_1_0/uController_mdm_1_0_ooc_trace.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_rst_clk_wiz_0_100M_0/uController_rst_clk_wiz_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uController_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_clk_wiz_1_3 || ORIG_REF_NAME==uController_clk_wiz_1_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_clk_wiz_1_3/uController_clk_wiz_1_3_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_326b_ila_lib_0 || ORIG_REF_NAME==bd_326b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/ip/ip_0/bd_326b_ila_lib_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/bd_0/bd_326b_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_0_0/uController_system_ila_0_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/pinout.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_FEB_fabric_0_0/FEB_fabric.srcs/constrs_1/new/timing.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uController_FEB_fabric_0_0 || ORIG_REF_NAME==uController_FEB_fabric_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f23a_ila_lib_0 || ORIG_REF_NAME==bd_f23a_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f23a_ila_lib_0 || ORIG_REF_NAME==bd_f23a_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/ip/ip_0/bd_f23a_ila_lib_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/bd_0/bd_f23a_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/ip/uController_system_ila_1_0/uController_system_ila_1_0_ooc.xdc

# XDC: c:/v22.2/FEB_uController/FEB_uController.gen/sources_1/bd/uController/uController_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uController'. Do not add the DONT_TOUCH constraint.
