# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/bd/BareMetal_TestDDR/ip/BareMetal_TestDDR_TestDDR_top_0_0/BareMetal_TestDDR_TestDDR_top_0_0.xci
# IP: The module: 'BareMetal_TestDDR_TestDDR_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/SCFIFO_1kx16/SCFIFO_1kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1kx16 || ORIG_REF_NAME==SCFIFO_1kx16} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/bd/BareMetal_TestDDR/ip/BareMetal_TestDDR_TestDDR_top_0_0/BareMetal_TestDDR_TestDDR_top_0_0.xci
# IP: The module: 'BareMetal_TestDDR_TestDDR_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/ila_0/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/SCFIFO_1kx16/SCFIFO_1kx16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1kx16 || ORIG_REF_NAME==SCFIFO_1kx16} -quiet] -quiet

# IP: C:/v22.2/Test_DDR/Test_DDR.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet
