# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v22.2/FEB_AXI_test/FEB_AXI_test.srcs/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2.xci
# IP: The module: 'ARTY_test_clk_wiz_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_test_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_test_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_test_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/v22.2/FEB_AXI_test/FEB_AXI_test.srcs/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2.xci
# IP: The module: 'ARTY_test_clk_wiz_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_test_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_test_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_test_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
