# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# IP: ip/iuCD_FIFO/iuCD_FIFO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] -quiet

# Block Designs: bd/ARTY_test/ARTY_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test || ORIG_REF_NAME==ARTY_test} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_axi_gpio_0_0/ARTY_test_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_axi_gpio_0_0 || ORIG_REF_NAME==ARTY_test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_axi_uartlite_0_0/ARTY_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_axi_uartlite_0_0 || ORIG_REF_NAME==ARTY_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_microblaze_0_0/ARTY_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_microblaze_0_0 || ORIG_REF_NAME==ARTY_test_microblaze_0_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_dlmb_v10_0/ARTY_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_dlmb_v10_0 || ORIG_REF_NAME==ARTY_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_ilmb_v10_0/ARTY_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_ilmb_v10_0 || ORIG_REF_NAME==ARTY_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_dlmb_bram_if_cntlr_0/ARTY_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ARTY_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_ilmb_bram_if_cntlr_0/ARTY_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ARTY_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_lmb_bram_0/ARTY_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_lmb_bram_0 || ORIG_REF_NAME==ARTY_test_lmb_bram_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_mdm_1_0/ARTY_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_mdm_1_0 || ORIG_REF_NAME==ARTY_test_mdm_1_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_rst_clk_wiz_0_100M_0/ARTY_test_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==ARTY_test_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_xbar_0/ARTY_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_xbar_0 || ORIG_REF_NAME==ARTY_test_xbar_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_microblaze_0_axi_periph_0/ARTY_test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ARTY_test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_FEB_AXI_Interface_0_0/ARTY_test_FEB_AXI_Interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_FEB_AXI_Interface_0_0 || ORIG_REF_NAME==ARTY_test_FEB_AXI_Interface_0_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_clk_wiz_0_2/ARTY_test_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_clk_wiz_0_2 || ORIG_REF_NAME==ARTY_test_clk_wiz_0_2} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_clk_wiz_1_1/ARTY_test_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_clk_wiz_1_1 || ORIG_REF_NAME==ARTY_test_clk_wiz_1_1} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_system_ila_0_0/ARTY_test_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_system_ila_0_0 || ORIG_REF_NAME==ARTY_test_system_ila_0_0} -quiet] -quiet

# IP: bd/ARTY_test/ip/ARTY_test_FEB_test_0_0/ARTY_test_FEB_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ARTY_test_FEB_test_0_0 || ORIG_REF_NAME==ARTY_test_FEB_test_0_0} -quiet] -quiet

# IP: ip/AFEemu_ila/AFEemu_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu_ila || ORIG_REF_NAME==AFEemu_ila} -quiet] -quiet

# IP: ip/AFEemu/AFEemu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AFEemu || ORIG_REF_NAME==AFEemu} -quiet] -quiet

# IP: ip/iuCD_FIFO/iuCD_FIFO.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iuCD_FIFO || ORIG_REF_NAME==iuCD_FIFO} -quiet] -quiet

# XDC: c:/v22.2/FEB_AXI_test/FEB_AXI_test.gen/sources_1/bd/ARTY_test/ARTY_test_ooc.xdc
